AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploys a publicly accessible RDS MySQL 8.0.40 instance'

Parameters:
  VPCId:
    Description: "VPC ID for assignment-vpc"
    Type: AWS::EC2::VPC::Id
    Default: vpc-069cb63e9147cfd93  # Replace with actual VPC ID

  PublicSubnet1Id:
    Description: "Public Subnet 1 ID"
    Type: AWS::EC2::Subnet::Id
    Default: subnet-06b18ddb3a32aa801  # Replace with actual Public Subnet ID

  PublicSubnet2Id:
    Description: "Public Subnet 2 ID"
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0505c44bf7524dde4  # Replace with actual Public Subnet ID

  YourIpAddress:
    Description: "Your Public IP or wildcard to allow MySQL access"
    Type: String
    Default: "0.0.0.0/0"  # Replace with your actual IP to secure access

Resources:
  # RDS Security Group (Allows External Access)
  PublicRDSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Publicly Accessible MySQL RDS"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref YourIpAddress  # Only allows your PC to connect
      Tags:
        - Key: Name
          Value: assignment-public-rds-security-group

  # RDS Subnet Group (For Public Subnets)
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS in assignment-vpc"
      SubnetIds:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id

  # Publicly Accessible RDS MySQL Instance
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: db-finance-app-assignment
      Engine: mysql
      EngineVersion: "8.0.40"
      DBInstanceClass: db.t3.small
      AllocatedStorage: 100
      StorageType: gp2
      MasterUsername: admin
      MasterUserPassword: whatever # Set password here
      VPCSecurityGroups:
        - !Ref PublicRDSecurityGroup
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true  # Now accessible over the internet
      BackupRetentionPeriod: 7
      DeletionProtection: false

Outputs:
  DBEndpoint:
    Description: "Public RDS MySQL Endpoint"
    Value: !GetAtt MyDBInstance.Endpoint.Address
